module.exports = {
  // USERS ERRORS.
  ERROR_CREATING_USER: 'ERROR_CREATING_USER',
  ERROR_FINDING_USERS: 'ERROR_FINDING_USERS',
  ERROR_FINDING_USER_BY_ID: 'ERROR_FINDING_USER_BY_ID',
  ERROR_UPDATING_USER_BY_ID: 'ERROR_UPDATING_USER_BY_ID',
  // ROOM ERRORS.
  ERROR_CREATING_ROOM: 'ERROR_CREATING_ROOM',
  ERROR_FINDING_ROOMS: 'ERROR_FINDING_ROOMS',
  ERROR_FINDING_ROOM_BY_ID: 'ERROR_FINDING_ROOM_BY_ID',
  ERROR_UPDATING_ROOM_BY_ID: 'ERROR_UPDATING_ROOM_BY_ID',
  ERROR_FINDING_ROOM_MESSAGES: 'ERROR_FINDING_ROOM_MESSAGES',
  // MESSAGES ERRORS.
  ERROR_FINDING_MESSAGES: 'ERROR_FINDING_MESSAGES',
  ERROR_CREATING_MESSAGE: 'ERROR_CREATING_MESSAGE',
  ERROR_UPDATING_MESSAGE_BY_ID: 'ERROR_UPDATING_MESSAGE_BY_ID',
  ERROR_FINDING_MESSAGE_BY_ID: 'ERROR_FINDING_MESSAGE_BY_ID'
}